# User-editable config
input_folder: "../data/"
output_folder: "outputs/"

face_detector:
  type: "yolo"
  model_path: "models/yolov11l-face.pt"
  confidence: 0.3
  detection_image_size: 640

facial_landmarks_detector:
  type: "spiga"
  model_path: "models/spiga.pth"

anonymization_method: "black_box"
log_level: "info"
