# Internal defaults (you don't have to edit these to run the demo)
save_face_detection_visualization: false
save_facial_landmarks_visualization: false
max_frame_detection_lookback: 0
anonymization_padding_method: "ratio"
anonymization_padding_ratio: 0.75
anonymization_padding_constant: 96

# Logging defaults
process_console_log_level: "info"
save_log_file: false
log_file_log_level: "debug"
log_file_path: "process_log.txt"

# Evaluation defaults
evaluate_redetections: true
evaluate_identity_switches: true
max_evaluated_frames: 500
metrics:
  - identity_consistency
  - detection_accuracy

# Module defaults
identity_encoder_name: "arcface"
face_detector_name: "yolo"
facial_landmarks_detector_name: "spiga"
