# User-editable config
input_settings:
  input_folder: "data/"
  output_folder: "outputs/"
  restrict_access_to_saved: false

module_settings:
  face_detector_name: "yolo"
  facial_landmarks_detector_name: "spiga"
  anonymizer_name: "black_box"
  identity_encoder_name: "arcface"

anonymization_settings:
  # TODO - maybe add visualization settings
  save_face_detection_visualization: false
  save_facial_landmarks_visualization: false
  max_frame_detection_lookback: 0

evaluation_settings:
#  evaluate_redetections: true
#  evaluate_identity_switches: true
  max_evaluated_frames: 500
  evaluation_skipped_frames: 0
#  metrics:
#    - identity_consistency
#    - detection_accuracy

logging_settings:
  process_console_log_level: "info"
  process_file_log_level: "debug"
  process_log_filepath: "logs/process_log.txt"

  log_anonymization_result: true
  anonymization_result_log_filepath: "logs/anonymization_results.txt"

  log_frames_without_detections: true
  frames_without_detections_log_filepath: "logs/frames_without_detections.txt"
